apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sspp-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: deployments-channel
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/daviesbrown/sspp.git
    targetRevision: main
    path: infrastructure/k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: sspp-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
