apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sspp-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/daviesbrown/sspp.git
    targetRevision: main
    path: infrastructure/k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: sspp-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
